export const allProducts = [
  {
    id:1,
    name: 'Celestial Charm Loop',
    category: 'Bracelet',
    price: 68,
    material: "Gold",
    type: "Rising",
    image1: './Images/Bracelets/1-1.webp',
    image2: './Images/Bracelets/1-2.webp',
  },

  {
    id:2,
    name: 'Twilight Blossom Band',
    category: 'Bracelet',
    price: 54,
    material: "Gold",
    type: "Rising",
    image1: './Images/Bracelets/2-1.webp',
    image2: './Images/Bracelets/2-2.webp',
  },
  {
    id:3,
    name: 'Delicate Butterfly Link',
    category: 'Bracelet',
    price: 54,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/3-1.webp',
    image2: './Images/Bracelets/3-2.webp',
  },
  {
    id:4,
    name: 'Whispering Ocean Waves',
    category: 'Bracelet',
    price: 39,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/4-1.webp',
    image2: './Images/Bracelets/4-2.webp',
  },
  {
    id:5,
    name: 'Mystic Bloom Adornment',
    category: 'Bracelet',
    price: 15,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/5-1.webp',
    image2: './Images/Bracelets/5-2.webp',
  },
  {
    id:6,
    name: 'Golden Harmony Bnagle',
    category: 'Bracelet',
    price: 20,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/6-1.webp',
    image2: './Images/Bracelets/6-2.webp',
  },
  {
    id:7,
    name: 'Twilight Elegance Wrap',
    category: 'Bracelet',
    price: 18,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/7-1.webp',
    image2: './Images/Bracelets/7-2.webp',
  },
  {
    id:8,
    name: 'Celestial Sparkle Chain',
    category: 'Bracelet',
    price: 52,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/3-2.webp',
    image2: './Images/Bracelets/8-2.webp',
  },
  {
    id:9,
    name: 'Moonlit Whisper Bracelet',
    category: 'Bracelet',
    price: 66,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/9-1.webp',
    image2: './Images/Bracelets/9-2.webp',
  },
  {
    id:10,
    name: 'Etheral Gemstone GLow',
    category: 'Bracelet',
    price: 71,
    material: "Gold",
    type: "Emillia",
    image1: './Images/Bracelets/10-1.webp',
    image2: './Images/Bracelets/10-2.webp',
  },
  

  
];